# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name_plural': 'Models'},
        ),
        migrations.AlterField(
            model_name='models',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
